Enhanced NA Handling
ralhei/pyRserve pull request #25
Opened 2020-12-15 19:09 UTC by MaxTaggart

I know I'm wading into controversial water here, but there are cases where R's "NA" value is being converted into something unexpected in python. Specifically:

1. The first change addresses issue #21. In short, R `vector`s that contained `character` values and `NA` were causing `UnicodeDecodeErrors` as they were being parsed into `numpy` arrays. The change in `pyRserve/misc.py` now has the parser checking for R's `NA_character_` specifically and converting it to Python's `None`.

``` python
import pyRserve

conn = pyRserve.connect()

# Old behaivor
conn.eval("c('a', NA, 'b')") # => UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

# New behaivor
conn.eval("c('a', NA, 'b')") # => array(['a', None, 'b'], dtype=object)

```

2. Converting an R `vector` that contains booleans and `NA` produces a python `numpy` array of integers and `None`. The `None` is expected, but the integers are a surprise. The change in `pyRserve/rparser.py` produces a numpy array of booleans and `None`. 

``` python
import pyRserve

conn = pyRserve.connect()

# Old behaivor
conn.eval("c(TRUE, NA, FALSE)") # => array([1, None, 0], dtype=object)

# New behaivor
conn.eval("c(TRUE, NA, FALSE)") # => array([True, None, False], dtype=object)
```

2020-12-15 19:12 UTC, MaxTaggart commented
As soon as I can get the tests to run I'll mark is as "Ready for review". Rserve on my machine must have been installed differently than on yours because the `testtools.py` module isn't detecting the path correctly.

2021-03-23 19:25 UTC, ralhei commented
Hi Max,
did you get any progress on this issue? 
R

2021-04-13 12:53 UTC, ralhei requested changes
Hi Max,
thanks a lot for your contribution. I'm happy with your solution, and the tests run successfully on my machine. Please have a look at my two comments. Also please rebase on master because I've just fixed some other deprecation warning code in there.

2021-04-13 12:53 UTC, ralhei commented on pyRserve/rparser.py
> +            data = numpy.frombuffer(raw[:numBools], dtype=numpy.int8).astype(numpy.object)
`numpy.object` has been deprecated, would you mind to use plain `object` instead?

2021-04-13 12:53 UTC, ralhei commented on pyRserve/rparser.py
> +            return data
I'd prefer an `else`-clause here so we have just one return statement at the end.

2021-04-21 22:38 UTC, MaxTaggart commented
Hey, @ralhei . Sorry for the wait. I have made the two changes you suggested and re-based onto `master`, let me know if anything still looks squirrelly. And thanks for the package!

2021-04-24 18:07 UTC, ralhei commented
Hi Max,
thanks for your changes. However it is never a good idea to merge changes from master into a working tree because the history tree really gets messed up. So please (in the future) always 'rebase' your working tree onto master and avoid a merge. 
I'll accept your change anyway, just to get ahead with everything.
Cheers,
Ralph

2021-04-24 18:31 UTC, ralhei commented
Sorry, changed my mind, because changes from Chad and myself would be part of the pull request. 

Before running the next command please create a patch for your changes, just to be safe ;-)

Then the command to get rid of the merge-commit in your history is to run `git rebase --onto 62c4d36e^ 62c4d36e HEAD`
Finally push (possibly with --force) again. We hopefully then have a clean pull request.

2021-06-19 16:17 UTC, ralhei commented
Hi Max,
in order to get this PR finally done I've finally merge your code myself in the proposed way. Due to that I will now close the PR.
Thanks a lot for your contribution.

2021-06-19 16:17 UTC, closed without merging